platform :ios, '10.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'RSInterfaceKit' do
  pod "RSInterfaceKit", :path => "../"
end

target 'Tests' do
  pod "RSInterfaceKit", :path => "../"
end
