use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'RSInterfaceKit', :exclusive => true do
  pod "RSInterfaceKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "RSInterfaceKit", :path => "../"

  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
end
