# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
# - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

language: objective-c
cache: cocoapods
podfile: Example/Podfile
osx_image: xcode8.2
rvm: 2.2.2  
before_install:
- gem install bundler
- bundle install
- bundle exec pod install --project-directory=Example
install:
script:
- set -o pipefail && xcodebuild clean test analyze -workspace Example/RSInterfaceKit.xcworkspace -scheme RSInterfaceKit-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.0' | xcpretty -c
- bundle exec pod lib lint --quick
